apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-uonz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0068-tenant/tkrw-pr712-0075-0068-app/devfile-sample-uonz@sha256:ac86337077a463261849c603cdc94f4851de04a7bbedc5c8f70bbfb4b356acdf
        name: my-nodejs
        resources: {}
status: {}
